block.settings.chess_kingfish:
  type: block_settings
  label: 'Example configurable text block configuration'
  mapping:
    chess_kingfish_block_string:
      type: text
      label: 'Block contents'
